[2024-07-08T05:30:01.426+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T05:30:01.434+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T05:30:01.434+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-08T05:30:01.450+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-08 05:25:00+00:00
[2024-07-08T05:30:01.456+0000] {standard_task_runner.py:57} INFO - Started process 2739 to run task
[2024-07-08T05:30:01.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-08T05:25:00+00:00', '--job-id', '3530', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpoombquoy']
[2024-07-08T05:30:01.466+0000] {standard_task_runner.py:85} INFO - Job 3530: Subtask task_validate_submissions
[2024-07-08T05:30:01.543+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-08T05:30:01.650+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T05:25:00+00:00'
[2024-07-08T05:30:01.652+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-08T05:30:01.666+0000] {logging_mixin.py:151} INFO - 2024-01-31 00:00:00
[2024-07-08T05:30:01.666+0000] {logging_mixin.py:151} INFO - {'name': '1HK', 'version': 'v0', 'bic4': '0000', 'date': '2024-01-31 00:00:00'}
[2024-07-08T05:30:01.668+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-08T05:30:01.669+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-08T05:30:01.678+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240708T052500, start_date=20240708T053001, end_date=20240708T053001
[2024-07-08T05:30:01.715+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-08T05:30:01.732+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T10:13:16.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:13:16.987+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:13:16.987+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-08T10:13:17.031+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-08 05:25:00+00:00
[2024-07-08T10:13:17.046+0000] {standard_task_runner.py:57} INFO - Started process 7626 to run task
[2024-07-08T10:13:17.079+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-08T05:25:00+00:00', '--job-id', '3700', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmptfa4236c']
[2024-07-08T10:13:17.085+0000] {standard_task_runner.py:85} INFO - Job 3700: Subtask task_validate_submissions
[2024-07-08T10:13:17.247+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-08T10:13:19.883+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T05:25:00+00:00'
[2024-07-08T10:13:21.864+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/dependancy_check.py", line 15, in get_hello
    connection = psycopg2.connect(user="docker",
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "posql-postgres_omor-1" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 49, in validate_submissions
    get_hello()
  File "/opt/airflow/dags/dependancy_check.py", line 266, in get_hello
    if connection:
UnboundLocalError: local variable 'connection' referenced before assignment
[2024-07-08T10:13:22.105+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240708T052500, start_date=20240708T101316, end_date=20240708T101322
[2024-07-08T10:13:22.213+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3700 for task task_validate_submissions (local variable 'connection' referenced before assignment; 7626)
[2024-07-08T10:13:22.246+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-08T10:13:22.298+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T10:21:27.893+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:21:28.584+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:21:28.584+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-08T10:21:28.650+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-08 05:25:00+00:00
[2024-07-08T10:21:28.665+0000] {standard_task_runner.py:57} INFO - Started process 7876 to run task
[2024-07-08T10:21:28.670+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-08T05:25:00+00:00', '--job-id', '3749', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp71yq9dqf']
[2024-07-08T10:21:28.675+0000] {standard_task_runner.py:85} INFO - Job 3749: Subtask task_validate_submissions
[2024-07-08T10:21:28.751+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-08T10:21:28.881+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T05:25:00+00:00'
[2024-07-08T10:21:28.896+0000] {logging_mixin.py:151} INFO - (1, '+OK 1 1720002855705013288', 'khalimzod@list.ru_374_2024-07-03 12:20:28.539851_<000701dacd34$7fa4a120$7eede360$@nbt.tj>', datetime.datetime(2024, 7, 3, 15, 33, 52, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 7, 3, 12, 20, 29, tzinfo=datetime.timezone.utc), 'Халимзод Исмоил Абдурахмон <ihalimzod@nbt.tj>', 1, 1)
[2024-07-08T10:21:28.899+0000] {logging_mixin.py:151} INFO - 2024-01-31 00:00:00
[2024-07-08T10:21:28.899+0000] {logging_mixin.py:151} INFO - {'name': '1HK', 'version': 'v0', 'bic4': '0000', 'date': '2024-01-31 00:00:00'}
[2024-07-08T10:21:28.900+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-08T10:21:28.901+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-08T10:21:28.915+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240708T052500, start_date=20240708T102128, end_date=20240708T102128
[2024-07-08T10:21:28.963+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-08T10:21:28.990+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T10:25:40.502+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:25:40.548+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:25:40.551+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-08T10:25:40.602+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-08 05:25:00+00:00
[2024-07-08T10:25:40.629+0000] {standard_task_runner.py:57} INFO - Started process 8495 to run task
[2024-07-08T10:25:40.644+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-08T05:25:00+00:00', '--job-id', '3927', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpvx5tkkqn']
[2024-07-08T10:25:40.678+0000] {standard_task_runner.py:85} INFO - Job 3927: Subtask task_validate_submissions
[2024-07-08T10:25:40.880+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-08T10:25:41.102+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T05:25:00+00:00'
[2024-07-08T10:25:41.158+0000] {logging_mixin.py:151} INFO - (1, '+OK 1 1720002855705013288', 'khalimzod@list.ru_374_2024-07-03 12:20:28.539851_<000701dacd34$7fa4a120$7eede360$@nbt.tj>', datetime.datetime(2024, 7, 3, 15, 33, 52, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 7, 3, 12, 20, 29, tzinfo=datetime.timezone.utc), 'Халимзод Исмоил Абдурахмон <ihalimzod@nbt.tj>', 1, 1)
[2024-07-08T10:25:41.161+0000] {logging_mixin.py:151} INFO - 2024-01-31 00:00:00
[2024-07-08T10:25:41.161+0000] {logging_mixin.py:151} INFO - {'name': '1HK', 'version': 'v0', 'bic4': '0000', 'date': '2024-01-31 00:00:00'}
[2024-07-08T10:25:41.169+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-08T10:25:41.169+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-08T10:25:41.199+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240708T052500, start_date=20240708T102540, end_date=20240708T102541
[2024-07-08T10:25:41.278+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-08T10:25:41.316+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T10:26:29.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:26:29.287+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [queued]>
[2024-07-08T10:26:29.287+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-08T10:26:29.319+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-08 05:25:00+00:00
[2024-07-08T10:26:29.330+0000] {standard_task_runner.py:57} INFO - Started process 8604 to run task
[2024-07-08T10:26:29.351+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-08T05:25:00+00:00', '--job-id', '3966', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp3lwj_l8e']
[2024-07-08T10:26:29.359+0000] {standard_task_runner.py:85} INFO - Job 3966: Subtask task_validate_submissions
[2024-07-08T10:26:29.430+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-08T05:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-08T10:26:29.586+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T05:25:00+00:00'
[2024-07-08T10:26:29.600+0000] {logging_mixin.py:151} INFO - (1, '+OK 1 1720002855705013288', 'khalimzod@list.ru_374_2024-07-03 12:20:28.539851_<000701dacd34$7fa4a120$7eede360$@nbt.tj>', datetime.datetime(2024, 7, 3, 15, 33, 52, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 7, 3, 12, 20, 29, tzinfo=datetime.timezone.utc), 'Халимзод Исмоил Абдурахмон <ihalimzod@nbt.tj>', 1, 1)
[2024-07-08T10:26:29.603+0000] {logging_mixin.py:151} INFO - 2024-01-31 00:00:00
[2024-07-08T10:26:29.603+0000] {logging_mixin.py:151} INFO - {'name': '1HK', 'version': 'v0', 'bic4': '0000', 'date': '2024-01-31 00:00:00'}
[2024-07-08T10:26:29.606+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-08T10:26:29.607+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-08T10:26:29.627+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240708T052500, start_date=20240708T102629, end_date=20240708T102629
[2024-07-08T10:26:29.654+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-08T10:26:29.677+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
