[2024-07-25T04:59:14.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-25T04:59:11.998498+00:00 [queued]>
[2024-07-25T04:59:14.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-25T04:59:11.998498+00:00 [queued]>
[2024-07-25T04:59:14.848+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-25T04:59:14.862+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-25 04:59:11.998498+00:00
[2024-07-25T04:59:14.868+0000] {standard_task_runner.py:57} INFO - Started process 126650 to run task
[2024-07-25T04:59:14.876+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'manual__2024-07-25T04:59:11.998498+00:00', '--job-id', '8064', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp4qb46kam']
[2024-07-25T04:59:14.880+0000] {standard_task_runner.py:85} INFO - Job 8064: Subtask task_validate_submissions
[2024-07-25T04:59:15.323+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-25T04:59:11.998498+00:00 [running]> on host 6f4ef5488251
[2024-07-25T04:59:15.546+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T04:59:11.998498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T04:59:11.998498+00:00'
[2024-07-25T04:59:15.547+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-25T04:59:15.562+0000] {logging_mixin.py:151} INFO - 2024-06-30 00:00:00
[2024-07-25T04:59:16.057+0000] {logging_mixin.py:151} INFO - <openpyxl.workbook.workbook.Workbook object at 0x7f8a1b417520>
[2024-07-25T04:59:16.693+0000] {logging_mixin.py:151} INFO - <openpyxl.workbook.workbook.Workbook object at 0x7f8a1b477c40>
[2024-07-25T04:59:17.046+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-25T04:59:17.046+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-25T04:59:17.060+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240725T045911, start_date=20240725T045914, end_date=20240725T045917
[2024-07-25T04:59:17.099+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-25T04:59:17.126+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
