[2024-07-03T09:57:27.870+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T09:57:27.883+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T09:57:27.883+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:27.899+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:35:00+00:00
[2024-07-03T09:57:27.910+0000] {standard_task_runner.py:57} INFO - Started process 20539 to run task
[2024-07-03T09:57:27.924+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:35:00+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpognf0hy8']
[2024-07-03T09:57:27.926+0000] {standard_task_runner.py:85} INFO - Job 348: Subtask id_task_get_emails
[2024-07-03T09:57:28.040+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:28.162+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:35:00+00:00'
[2024-07-03T09:57:28.163+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:28.163+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:28.184+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T083500, start_date=20240703T095727, end_date=20240703T095728
[2024-07-03T09:57:28.212+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 348 for task id_task_get_emails (name 'json' is not defined; 20539)
[2024-07-03T09:57:28.250+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:28.279+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:58.254+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T12:04:58.274+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T12:04:58.274+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:58.293+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:35:00+00:00
[2024-07-03T12:04:58.299+0000] {standard_task_runner.py:57} INFO - Started process 23357 to run task
[2024-07-03T12:04:58.311+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:35:00+00:00', '--job-id', '789', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpj3p2yqai']
[2024-07-03T12:04:58.313+0000] {standard_task_runner.py:85} INFO - Job 789: Subtask id_task_get_emails
[2024-07-03T12:04:58.377+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:58.475+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:35:00+00:00'
[2024-07-03T12:04:58.475+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:58.476+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:58.476533_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:58.476+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:58.476734_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:58.476+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:58.476873_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:58.841+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:59.311+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:59.722+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:59.722530_conneciton to db is set.
[2024-07-03T12:04:59.730+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:59.748+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T083500, start_date=20240703T120458, end_date=20240703T120459
[2024-07-03T12:04:59.767+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 789 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23357)
[2024-07-03T12:04:59.809+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:59.842+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:23:05.925+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T12:23:05.942+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [queued]>
[2024-07-03T12:23:05.942+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:23:05.954+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:35:00+00:00
[2024-07-03T12:23:05.958+0000] {standard_task_runner.py:57} INFO - Started process 24226 to run task
[2024-07-03T12:23:05.964+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:35:00+00:00', '--job-id', '1090', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp0w4zuttr']
[2024-07-03T12:23:05.965+0000] {standard_task_runner.py:85} INFO - Job 1090: Subtask id_task_get_emails
[2024-07-03T12:23:06.035+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:35:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:23:06.122+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:35:00+00:00'
[2024-07-03T12:23:06.123+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:23:06.126+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:06.126107_User@StatDep: EmailRobot in screated.
[2024-07-03T12:23:06.126+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:06.126500_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:23:06.126+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:06.126808_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:23:06.525+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:23:06.879+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:23:06.879+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:06.879730_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:23:06.880+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:23:06.912+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T083500, start_date=20240703T122305, end_date=20240703T122306
[2024-07-03T12:23:07.033+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:23:07.056+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
